apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: build-mage
  name: build-mage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: build-mage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: build-mage
    spec:
      containers:
        - image: lv-file
          name: build-mage
          resources: {}
      restartPolicy: Always
status: {}
