apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: files-es-index-all-office-files
  name: files-es-index-all-office-files
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: files-es-index-all-office-files
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: files-es-index-all-office-files
    spec:
      containers:
        - args:
            - python3
            - /app/bk_services/fs_es_index.py
          image: lv-file
          name: files-es-index-all-office-files
          resources: {}
          volumeMounts:
            - mountPath: /app/tmp
              name: files-es-index-all-office-files-claim0
            - mountPath: /app/fs-docs
              name: files-es-index-all-office-files-claim1
      restartPolicy: Always
      volumes:
        - name: files-es-index-all-office-files-claim0
          persistentVolumeClaim:
            claimName: files-es-index-all-office-files-claim0
        - name: files-es-index-all-office-files-claim1
          persistentVolumeClaim:
            claimName: files-es-index-all-office-files-claim1
status: {}
