apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: thumb-video
  name: thumb-video
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thumb-video
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: thumb-video
    spec:
      containers:
        - args:
            - python3
            - /app/bk_services/thumb_video.py
          image: lv-file
          name: thumb-video
          resources: {}
          volumeMounts:
            - mountPath: /app/tmp
              name: thumb-video-claim0
            - mountPath: /app/logs
              name: thumb-video-claim1
            - mountPath: /app/fs-docs
              name: thumb-video-claim2
      restartPolicy: Always
      volumes:
        - name: thumb-video-claim0
          persistentVolumeClaim:
            claimName: thumb-video-claim0
        - name: thumb-video-claim1
          persistentVolumeClaim:
            claimName: thumb-video-claim1
        - name: thumb-video-claim2
          persistentVolumeClaim:
            claimName: thumb-video-claim2
status: {}
