apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: thumb-office
  name: thumb-office
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thumb-office
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: thumb-office
    spec:
      containers:
        - args:
            - python3
            - /app/bk_services/thumb_office.py
          image: lv-file
          name: thumb-office
          resources: {}
          volumeMounts:
            - mountPath: /app/tmp
              name: thumb-office-claim0
            - mountPath: /app/fs-docs
              name: thumb-office-claim1
      restartPolicy: Always
      volumes:
        - name: thumb-office-claim0
          persistentVolumeClaim:
            claimName: thumb-office-claim0
        - name: thumb-office-claim1
          persistentVolumeClaim:
            claimName: thumb-office-claim1
status: {}
