apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - gunicorn
            - -w
            - "4"
            - --worker-class
            - uvicorn.workers.UvicornWorker
            - api_app:app
            - --bind
            - 0.0.0.0:80
          env:
            - name: file_server_api_url
              value: http://:/api
            - name: file_server_bind_ip
              value: 0.0.0.0
            - name: file_server_bind_port
              value: "80"
            - name: file_server_db_auth_source
              value: lv-docs
            - name: file_server_db_host
              value: 192.168.18.36
            - name: file_server_db_password
              value: "123456"
            - name: file_server_db_port
              value: "27018"
            - name: file_server_db_replica_set
            - name: file_server_db_username
              value: admin-doc
            - name: file_server_es_url
              value: '''http://,'''
            - name: file_server_root_url
              value: 'http://:'
            - name: file_server_use_os_config
              value: '''true'''
          image: lv-file
          name: lv-file-web
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /app/logs
              name: web-claim0
            - mountPath: /app/tmp
              name: web-claim1
      hostname: web
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
        - name: web-claim1
          persistentVolumeClaim:
            claimName: web-claim1
status: {}
