db_25:
#  host: localhost
#  port: 27017
  host: 172.16.7.25
  port: 27018
  username:
  password:
  tls: false
  authSource:
  tlsCAFile:
db:
  host: 192.168.18.36
  port: 27018
  username: 'admin-doc'
  password: '123456'
  authSource: 'lv-docs'
  replicaSet:
  authMechanism: SCRAM-SHA-1
# Default administrator database
admin_db_name_25: media-server
admin_db_name: lv-docs
# unvicorn server listener list all ip
binding_ip: 0.0.0.0
# univocorn listen port
binding_port: 8011
jinja_templates_dir: ./templates
static_dir: ./app_manager/static
api_host_dir: api
_host_name: 192.168.1.11
host_name: 172.16.13.72
host_schema: http
host_port: 8011
jwt:
  secret_key: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  algorithm: HS256
  access_token_expire_minutes: 480
tmp_upload_dir: ./tmp
elastic_search:
  server:
    - http://192.168.18.36:9200
  index: lv-files-server-v2

