db:
#  host: localhost
#  port: 27017
  host: 172.16.7.25
  port: 27018
  username:
  password:
  tls: false
  authSource:
  tlsCAFile:
# Default administrator database
admin_db_name: media-server
# unvicorn server listener list all ip
binding_ip: 0.0.0.0
# univocorn listen port
binding_port: 8011
jinja_templates_dir: ./templates
static_dir: ./app_manager/static
api_host_dir: api
_host_name: 192.168.1.11
host_name: 172.16.13.72
host_schema: http
host_port: 8011
jwt:
  secret_key: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  algorithm: HS256
  access_token_expire_minutes: 480
tmp_upload_dir: ./tmp
elastic_search:
  - http://localhost:9200
