db:
  host: 192.168.18.36
  port: 27018
  username: 'admin-doc'
  password: '123456'
  authSource: 'lv-docs'
  replicaSet: ''
  authMechanism: SCRAM-SHA-1
watch-path: /app/tmp #docker
watch-path-: /home/vmadmin/python/file-service-02/map/web-api/tmp-file-upload # khong docker
fs-docs-: /home/vmadmin/python/file-service-02/map/fs/share-docs #kg docker
fs-docs: /app/fs-docs #docker
libre-office-path: /usr/bin/soffice