apiVersion: v1
kind: Namespace
metadata:
  name: kafka-sn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
  namespace: kafka-sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVERS
              value: kafka-zookeeper:2888:3888
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
          image: confluentinc/cp-zookeeper:7.3.0
          name: kafka-zoo-keeper
          ports:
            - containerPort: 2181
          resources: {}
      hostname: kafka-zookeeper
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
  namespace: kafka-sn
spec:
  type: ClusterIP
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    app: kafka-zookeeper
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka-sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-broker
    spec:
      containers:
        - env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ADVERTISED_HOST
              value: $(MY_POD_IP)
            - name: ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-broker:19092 ,EXTERNAL://$(MY_POD_IP):9092 #,DOCKER://host.docker.internal:29092
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: "true"
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              value: kafka.security.authorizer.AclAuthorizer
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_JMX_HOSTNAME
              value: $(MY_POD_IP) #"kafka-broker:-127.0.0.1"
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            - name: KAFKA_LOG4J_LOGGERS
              value: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: kafka-zookeeper:2181
          image: confluentinc/cp-kafka:7.3.0
          name: kafka-broker
          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 9999
          resources: {}
      hostname: kafka-broker
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka-sn
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 30992
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    app: kafka-broker
status:
  loadBalancer: {}
