apiVersion: v1
kind: Namespace
metadata:
  name: kafka

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
      - name: zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  namespace: kafka
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-1
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#  namespace: kafka
#
#  labels:
#    name: kafka
#spec:
#  ports:
#  - port: 9092
#    name: kafka-port
#    protocol: TCP
##    nodePort: 30400
#  selector:
#    app: kafka
#    id: "0"
#  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_PORT
          value: "9092" #30718
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: $(MY_POD_IP)
#        - name: KAFKA_LISTENERS
#          value: "INTERNAL://$(MY_POD_IP):9090, EXTERNAL://:9092"
#        - name: KAFKA_ADVERTISED_LISTENERS
#          value: "INTERNAL://$(MY_POD_IP):9090,EXTERNAL://$(MY_POD_IP):9092"
#        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
#        - name: KAFKA_INTER_BROKER_LISTENER_NAME
#          value: INTERNAL
        #----------------------------------------
          #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          #      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
          #      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
          #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
          #      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        #zoo1.kafka:2181 TCP
          #zoo1.kafka:0 TCP
          #zoo1.kafka:2888 TCP
          #zoo1.kafka:0 TCP
          #zoo1.kafka:3888 TCP
          #zoo1.kafka:0 TCP
        #---------------------------------------

        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1.kafka:2181 # for default namespace use zoo1:2181. In this case namespace is kafka
#        - name: KAFKA_BROKER_ID
#          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
  labels:
    app: kafka
spec:
#  externalTrafficPolicy: Cluster
#  ipFamilies:
#    - IPv4
#  ipFamilyPolicy: PreferDualStack
  type: NodePort
#  ports:
#    - protocol: "TCP"
#      port: 9092
#      targetPort: 9092
#      nodePort: 30092
  ports:
  - port: 9092
    nodePort: 30092
    name: server
  selector:
    app: kafka