#----------------------------------------------------------
# The file use for deployment of simple Kylin for POC not for production into k8s
# Thou notice that 4 sections:
# 1- Namespace
# 2- Deploy app with name of xdoc-web run in container
# 3- Create service point to xdoc-web app with name xdoc-web-service
# 4- Expose xdoc-web-service via ingress
#----------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: kylin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kylin-app
  namespace: kylin
spec:
  selector:
    matchLabels:
      app: kylin-app
  replicas: 1
  template:
    metadata:
      labels:
        app: kylin-app
    spec:
      containers:
        - args:
            - sh
            - /admin/entrypoint.sh
          image: apachekylin/apache-kylin-standalone:4.0.0
          name: apache-kylin-standalone
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
          resources: { }
---
apiVersion: v1
kind: Service
metadata:
  name: kylin-service
  namespace: kylin
  labels:
    app: kylin-app
spec:
  type: NodePort
  selector:
    app: kylin-app
  ports:
  - port: 8082
    targetPort: 7070
    protocol: TCP
    nodePort: 31300
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: xdoc-web-ingress
#  namespace: xdoc-web
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
##    nginx.ingress.kubernetes.io/use-regex: "true"
##    nginx.ingress.kubernetes.io/rewrite-target: /$1
#
#spec:
#  ingressClassName: nginx #nginx or lv-file-ingress
#  rules:
##    - host: myservicea.foo.org
#     - http:
#        paths:
#          - pathType: Prefix
#            path: /lvfile
#            backend:
#              service:
#                name: xdoc-web-service
#                port:
#                  number: 8082
##  rules:
##    - http:
##        paths:
##          - pathType: Prefix
##            path: "/(.+)"
##            backend:
##              service:
##                name: xdoc-web-service
##                port:
##                  number: 8017
#
