---
name: "{FS_CRAWLER_INDEX}"
fs:
  url: /app/fs-docs
  update_rate: "30s"
  excludes:
  - "*/~*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false
  ocr:
    language: "eng"
    enabled: false
    pdf_strategy: "ocr_and_text"
    path: "C:\\Program Files\\Tesseract-OCR"
    data_path: "C:\\Program Files\\Tesseract-OCR\\tessdata"
    output_type: "txt"
  follow_symlinks: false

elasticsearch:
  nodes:
  - url: "{ES_URL}"

  bulk_size: 100
  flush_interval: "60s"
  byte_size: "10mb"
  ssl_verification: false
